---
version: "2"
services:
  assembly:
    container_name: assembly
    build: assembly/
    networks:
      - "box_fuse_net"
    volumes:
      - datavolume:/opt/java-projects/boxfuse-sample-java-war-hello/target/
  web:
    container_name: server
    build: server/
    networks:
      - "box_fuse_net"
      - "bridge"
    volumes:
      - datavolume:/var/lib/tomcat9/webapps/
    ports:
      - "80:8080"
    depends_on:
      - assembly
    environment:
      - CATALINA_HOME=/usr/share/tomcat9
      - CATALINA_BASE=/var/lib/tomcat9

volumes:
  datavolume:

networks:
  box_fuse_net:
  bridge:
    driver: bridge