---
version: "2"
services:
  assembly:
    container_name: assembly
    build: assembly/
    volumes:
      - datavolume:/opt/java-projects/boxfuse-sample-java-war-hello/target/
  web:
    container_name: server
    build: server/
    volumes:
      - datavolume:/var/lib/tomcat9/webapps/
    ports:
      - "80:8080"
    depends_on:
      - assembly

volumes:
  datavolume: